// <auto-generated>
// ReSharper disable AllRitegeDomain

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RitegeDomain.Database.Entities.Parking
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // abonne
    public class Abonne:IEntity
    {
        public int IdAbonne { get; set; } // idAbonne (Primary key)
        public bool ActiverAbonnement { get; set; } // activerAbonnement
        public bool? MultiEntree { get; set; } // multiEntree

        // Reverse navigation

        /// <summary>
        /// Child Affectationabonnements where [affectationabonnement].[idAbonne] point to this entity (affectationabonnement_FK_evenement_idAbonne)
        /// </summary>
        public virtual IEnumerable<Affectationabonnement> Affectationabonnements { get; set; } // affectationabonnement.affectationabonnement_FK_evenement_idAbonne

        public Abonne()
        {
            Affectationabonnements = new List<Affectationabonnement>();
        }
    }

}
// </auto-generated>
