// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RitegeDomain.Database.Entities.Parking
{
    // abonnement
    public class Abonnement : IEntity
    {
        public int IdAbonnement { get; set; } // idAbonnement (Primary key)
        public string NomAbonnement { get; set; } // nomAbonnement (length: 100)
        public string PeriodeAbonnement { get; set; } // periodeAbonnement (length: 100)
        public int? NombrePeriode { get; set; } // nombrePeriode
        public decimal Montant { get; set; } // montant
        public int? IdIntervalle { get; set; } // idIntervalle
        public int IdGroupeTarif { get; set; } // idGroupeTarif

        // Reverse navigation

        /// <summary>
        /// Child Affectationabonnements where [affectationabonnement].[idAbonnement] point to this entity (affectationabonnement_FK_idAbonnement)
        /// </summary>
        public virtual IEnumerable<Affectationabonnement> Affectationabonnements { get; set; } // affectationabonnement.affectationabonnement_FK_idAbonnement

        public Abonnement()
        {
            Affectationabonnements = new List<Affectationabonnement>();
        }
    }

}
// </auto-generated>
