// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RitegeDomain.Database.Entities.ParkingEntities
{
    // abonnement_parking
    public class AbonnementParking : IEntity
    {
        public int IdParking { get; set; } // idParking (Primary key)
        public int IdAbonnement { get; set; } // idAbonnement (Primary key)
    }

}
// </auto-generated>
