// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RitegeDomain.Database.Entities.Parking
{
    // affectationabonnement
    public class Affectationabonnement : IEntity
    {
        public int Idaffectationabonnement { get; set; } // idaffectationabonnement (Primary key)
        public int IdAbonne { get; set; } // idAbonne
        public int IdAbonnement { get; set; } // idAbonnement
        public int OccurenceAbonnement { get; set; } // occurenceAbonnement

        public DateTime DateAffectationabonnementcol { get; set; } // dateAffectationabonnementcol
        public DateTime DateActivation { get; set; } // dateActivation
        public DateTime DateDesactivation { get; set; } // dateDesactivation
        public bool EtatSync { get; set; } // etatSync
        public string EtatAffectation { get; set; } // etatAffectation (length: 100)

        // Foreign keys

        /// <summary>
        /// Parent Abonne pointed by [affectationabonnement].([IdAbonne]) (affectationabonnement_FK_evenement_idAbonne)
        /// </summary>
        public virtual Abonne Abonne { get; set; } // affectationabonnement_FK_evenement_idAbonne

        /// <summary>
        /// Parent Abonnement pointed by [affectationabonnement].([IdAbonnement]) (affectationabonnement_FK_idAbonnement)
        /// </summary>
        public virtual Abonnement Abonnement { get; set; } // affectationabonnement_FK_idAbonnement

        public Affectationabonnement()
        {
            OccurenceAbonnement = 1;
        }
    }

}
// </auto-generated>
