// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RitegeDomain.Database.Entities.ParkingEntities
{
    // sessions
    public class Borne : IEntity
    {
        public int IdBorne { get; set; } // idSessions (Primary key)
        public string NomBorne { get; set; } // logCaissier (length: 100)
        public int Sync { get; set; } // dateStart
        public string Flux { get; set; } // dateEnd
        public int IdParking { get; set; } // montant
    }

}
// </auto-generated>
