// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RitegeDomain.Database.Entities.ParkingEntities
{
    // sessions
    public class Caisse : IEntity
    {
        public int IdCaisse { get; set; } // idSessions (Primary key)
        public string NomCaisse { get; set; } // logCaissier (length: 100)
        public Int16 Sync { get; set; } // dateStart
        public string Flux { get; set; } // dateEnd
        public int IdParking { get; set; } // montant
    }

}
// </auto-generated>
