// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RitegeDomain.Database.Entities.ParkingEntities
{
    // sessions
    public class Session : IEntity
    {
        public int IdSessions { get; set; } // idSessions (Primary key)
        public int? idCaisse { get; set; } // idCaisse
        public string LogCaissier { get; set; } // logCaissier (length: 100)
        public DateTime? dateStart { get; set; } // dateStart
        public DateTime? dateEnd { get; set; } // dateEnd
        public decimal? Montant { get; set; } // montant
    }

}
// </auto-generated>
