// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RitegeDomain.Database.Entities.Parking
{
    // utilisateur
    public class Utilisateur : IEntity
    {
        public int IdUtilisateur { get; set; } // idUtilisateur (Primary key)
        public string Nom { get; set; } // nom (length: 100)
        public string Prenom { get; set; } // prenom (length: 100)
        public string Login { get; set; } // login (length: 100)
        public string MotDePasse { get; set; } // motDePasse (length: 1000)
        public bool Sync { get; set; } // Sync
        public string NumAccessCard { get; set; } // NumAccessCard (length: 100)
    }

}
// </auto-generated>
