// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RitegeDomain.Database.Entities.ControleAccess
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // controllers
    /// <summary>
    /// controleaccessdb.controllers
    /// </summary>
    public class Controller : IEntity
    {
        public short Code { get; set; } // Code (Primary key)
        public short Idnode { get; set; } // idnode
        public string Ipadr { get; set; } // ipadr (length: 50)
        public short Port { get; set; } // port
        public string Macadr { get; set; } // macadr (length: 20)
        public string ModelName { get; set; } // modelName (length: 20)
        public short IdSite { get; set; } // idSite
        public int Stat { get; set; } // Stat
    }

}
// </auto-generated>
