// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RitegeDomain.Database.Entities.ControleAccess
{
    // door
    /// <summary>
    /// controleaccessdb.door
    /// </summary>
    public class Door : IEntity
    {
        public short IdDoor { get; set; } // idDoor (Primary key)
        public short? DoorNumber { get; set; } // doorNumber
        public string DoorName { get; set; } // doorName (length: 20)
        public short? IdController { get; set; } // idControler
        public short? IdPorte { get; set; } // idPorte
        public short? Canal { get; set; } // canal
        public short? IdSite { get; set; } // idSite
        public short? Stat { get; set; } // stat
        public string TypeMateriel { get; set; } // TypeMateriel (length: 20)
        public string FonctionMateriel { get; set; } // FonctionMateriel (length: 20)
        public bool HasSlaveReader { get; set; } // hasSlaveReader
        public string Flow { get; set; } // flow (length: 10)
        public bool? Activated { get; set; } // activated
        public int? IdParking { get; set; }
    }

}
// </auto-generated>
