// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RitegeDomain.Database.Entities.ControleAccess
{
    // event
    /// <summary>
    /// controleaccessdb.event
    /// </summary>
    public class Event : IEntity
    {
        public long IndexEvent { get; set; } // indexEvent (Primary key)
        public DateTime DateEvent { get; set; } // dateEvent
        public string HeureEvent { get; set; } // HeureEvent (length: 8)
        public ushort DoorNumber { get; set; } // DoorNumber
        public ushort? UserNumber { get; set; } // userNumber
        public ushort CodeEvent { get; set; } // codeEvent
        public ushort CodeController { get; set; } // codeControler
        public ushort IndiceController { get; set; } // indiceControler
        public bool Selected { get; set; } // selected
        public string NumAccessCard { get; set; } // numAccessCard (length: 11)
        public short? Data12 { get; set; } // Data12
        public ushort? Flux { get; set; } // Flux
    }

}
// </auto-generated>
