// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace RitegeDomain.Database.Entities.ControleAccess
{
    // eventtype
    /// <summary>
    /// controleaccessdb.eventtype
    /// </summary>
    public class Eventtype : IEntity
    {
        public short CodeTypeEvent { get; set; } // codeTypeEvent (Primary key)
        public string DescEvent { get; set; } // descEvent (length: 200)
        public bool WithUser { get; set; } // withUser
        public string TypeAcces { get; set; } // typeAcces (length: 10)
        public string KeyTypeEvent { get; set; } // keyTypeEvent (length: 20)

        public Eventtype()
        {
            WithUser = false;
        }
    }

}
// </auto-generated>
